### ISSUE TITLE
Tutorial links are broken

### ISSUE THREAD

**Issue by pjc0247** [microsoft/LLVMSharp#107]
https://github.com/microsoft/LLVMSharp#kaleidoscope-tutorials

Chapter 3~5 does not work

**Comment by ice1000** [comment]
They're in https://github.com/microsoft/LLVMSharp/tree/master/samples/KaleidoscopeTutorial

Btw https://ice1000.org/llvm-cs/en/

**Comment by tannergooding** [comment]
Happy to take a PR if someone wants to fix these. Otherwise, I'll try to get to it this weekend.

**Comment by ice1000** [comment]
PRed!
