### ISSUE TITLE
ClangPInvokeGenerator Script is gone

### ISSUE THREAD

**Issue by talyian** [microsoft/LLVMSharp#113]
it was removed as part of cleanup at https://github.com/microsoft/LLVMSharp/commit/19a14a7a2af5b4fbe8973e5dadcfe782869fb43e#diff-6ee4afc3584f3c677a11a8b9a74ea1bb

but now it's unclear the incantations used to freshly generate source from llvm-c-8 headers. 

At the very least the something resembling 

`dotnet run --m LLVM --p LLVM --namespace LLVMSharp --output Generated.tmp.cs --libraryPath $1 --include $2 --file $2/llvm-c/Analysis.h --file $2/llvm-c/BitReader.h --file $2/llvm-c/BitWriter.h --file $2/llvm-c/Comdat.h --file $2/llvm-c/Core.h --file $2/llvm-c/DataTypes.h --file $2/llvm-c/DebugInfo.h --file $2/llvm-c/Disassembler.h --file $2/llvm-c/DisassemblerTypes.h --file $2/llvm-c/Error.h --file $2/llvm-c/ErrorHandling.h --file $2/llvm-c/ExecutionEngine.h --file $2/llvm-c/Initialization.h --file $2/llvm-c/IRReader.h --file $2/llvm-c/Linker.h --file $2/llvm-c/LinkTimeOptimizer.h --file $2/llvm-c/lto.h --file $2/llvm-c/Object.h --file $2/llvm-c/OptRemarks.h --file $2/llvm-c/OrcBindings.h --file $2/llvm-c/Support.h --file $2/llvm-c/Target.h --file $2/llvm-c/TargetMachine.h --file $2/llvm-c/Types.h --file $2/llvm-c/Transforms/AggressiveInstCombine.h --file $2/llvm-c/Transforms/Coroutines.h --file $2/llvm-c/Transforms/InstCombine.h --file $2/llvm-c/Transforms/IPO.h --file $2/llvm-c/Transforms/PassManagerBuilder.h --file $2/llvm-c/Transforms/Scalar.h --file $2/llvm-c/Transforms/Utils.h --file $2/llvm-c/Transforms/Vectorize.h --e LLVMDisasmInstruction --e LLVMGetBufferStart --e LLVMGetDiagInfoDescription --e LLVMGetDefaultTargetTriple --e LLVMCopyStringRepOfTargetData --e LLVMGetTargetMachineTriple --e LLVMGetTargetMachineCPU --e LLVMGetTargetMachineFeatureString --e LLVMPrintTypeToString --e LLVMCreateMessage --e LLVMDisposeMessage --e LLVMPrintModuleToString --e LLVMPrintValueToString --e LLVMOrcDisposeMangledSymbol --e LLVMTargetMachineEmitToFile --e LLVMInitializeCore --e LLVMAddInstructionCombiningPass` from the old script should be maintained

**Comment by tannergooding** [comment]
It was removed as it was undesirable to continue maintaining a separate copy of clangsharp in the llvmsharp repo.

For right now, there is a separate run target in the ClangSharp repo here: <https://github.com/microsoft/ClangSharp/blob/master/sources/ClangSharpPInvokeGenerator/Properties/launchSettings.json> that represents the exact args used to generate the current LLVMSharp sources.

Once https://github.com/microsoft/ClangSharp/issues/46 is resolved, it will likely be updated such that `LLVMSharp` has a script which will pull down the `ClangSharpPInvokeGenerator` global tool and which will regenerate the sources locally.

**Comment by mjsabby** [comment]
@tannergooding can this be closed?

**Comment by tannergooding** [comment]
Yes, I think so. The only thing that could really be done additionally is to add a `-generate` option to the build scripts which invokes the global tool.
