### ISSUE TITLE
Native library not copied to output directory

### ISSUE THREAD

**Issue by TillAlex** [microsoft/LLVMSharp#115]
I am referencing the libLLVM 8.0 nuget package from a .NET standard 2.0 which is referenced by a .NET Core 2.0 as well as a .NET Framework 4.7.1 project. In both cases the libLLVM is not copied to the output folder.

Even if I reference the libLLVM.runtime.win-x64 Nuget package directly libLLVM.dll is not copied. Currently the only way to make it work is referencing libLLVM.dll from the nuget folder and set "Copy if newer".

Is there anything I am missing? Is the libLLVM 8.0 Nuget package supposed to copy the correct runtime library automatically?

**Comment by mjsabby** [comment]
I think the way nuget works is you may have to publish to the specific RID. Can you try dotnet publish -c Release -r win-x64 and see if it gets placed here?

**Comment by TillAlex** [comment]
Thanks for the hint. Using an explictit runtime identifier the native library gets placed. To make it work in Visual Studio I had to add

`<RuntimeIdentifier>win-x64</RuntimeIdentifier>`

to the project file.

**Comment by tannergooding** [comment]
I would recommend `<RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == ''">$(NETCoreSdkRuntimeIdentifier)</RuntimeIdentifier>`.

The above will use the given RID if one is specified (which allows cross-compiling, for example) and otherwise defaults to the RID of the .NET SDK that the build is actively being driven by (which should ensure you get something that works for the current machine).

**Comment by TillAlex** [comment]
@tannergooding Would be great to automatically use the correct RuntimeIdentifier. Unfortunately your idea does not work on my machine. Seems that NETCoreSdkRuntimeIdentifier is not set here. Any idea what I am doing wrong?

**Comment by tannergooding** [comment]
Are you building with `msbuild` rather than `dotnet build` or `dotnet msbuild`?

**Comment by TillAlex** [comment]
It does not work no matter if I am using dotnet build or Visual Studio 2019.
