### ISSUE TITLE
Update to LLVM v9.0.0

### ISSUE THREAD

**Issue by tannergooding** [microsoft/LLVMSharp#116]
LLVM v9.0.0 was just released and both libLLVM and the bindings should be updated to use it.

**Comment by tannergooding** [comment]
Most, but not all, of the pre-built binaries are up now (http://releases.llvm.org/download.html#9.0.0), so I can likely start on this soon.

**Comment by cloudrex** [comment]
Any updates on this?

**Comment by tannergooding** [comment]
The libLLVM binaries are not built for the majority of the platforms by default, so it will require some time/effort to build them manually instead.

**Comment by tannergooding** [comment]
I have machines setup for the various distro's that are built by default. I've started the work on getting libLLVM built for each.

**Comment by tannergooding** [comment]
I have win-x86, win-x64 done (pre-built)

I have also completed ubuntu-1604, ubuntu-1804, ubuntu-1904, freebsd-x86, and freebsd-x64 (locally built, as pre-built binaries don't exit)

The macOS build is going now and packages can start being pushed once that completes.

I still need to build linux-arm, linux-arm64, and sles to round out the package list.

**Comment by tannergooding** [comment]
This is done now. I'm logging issue tracking the remaining rid specific packages.
