### ISSUE TITLE
Wrong libLLVM.so for linux-arm and linux-arm64

### ISSUE THREAD

**Issue by TillAlex** [microsoft/LLVMSharp#117]
It seems that the nuget runtime packages for linux contain wrong binaries:

`nvidia@jetson-0423818076660:~$ file .nuget/packages/libllvm.runtime.linux-arm64/8.0.0/runtimes/linux-arm64/native/libLLVM.so 
.nuget/packages/libllvm.runtime.linux-arm64/8.0.0/runtimes/linux-arm64/native/libLLVM.so: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=5d6dde93e14328b16023d7e59cb6dc2265436849, not stripped`

Calling llvmSharp results in DLLNotFoundExceptions. When using libLLVM8 from the ubuntu repositories instead llvmSharp works fine.

**Comment by tannergooding** [comment]
I'll see about getting the correct version up for this as part of the getting the libLLVM 9 packages up.

**Comment by TillAlex** [comment]
Thanks in advance!

**Comment by TillAlex** [comment]
In the meantime I am using binaries from the ubuntu package. However the library is named libLLVM8.so here. I can fix this by creating a symlink, but I am asking myself where this should be fixed correctly. 

Is it expected that the package maintainers create a symlink libLLVM.so -> libLLVM8.so or should LLVMSharp use libLLVM8 as the library path in the DllImports?

**Comment by tannergooding** [comment]
This should now be resolved for LLVM 9 and 10. For 10, there will be a DllImportResolver that checks the well-known symlink names: https://github.com/microsoft/LLVMSharp/pull/132
