### ISSUE TITLE
RID linux-x64 for CoreRT

### ISSUE THREAD

**Issue by yowl** [microsoft/LLVMSharp#130]
Hi,  I'm trying to fix the linux build of the Wasm backend of CoreRT (https://github.com/dotnet/corert) and I think I have a problem with LLVMSharp and more specifically libLLVM.  When CoreRT builds it uses a rid of `linux-x64` goes which into `$__NugetRuntimeId`  which it passes to `dotnet build` as `/p:NuPkgRid=$__NugetRuntimeId`  .  From what I can see this RID is not present for libLLVM, i.e. its not in the packages `libllvm/9.0.0/runtime.json` file (https://github.com/microsoft/LLVMSharp/blob/master/packages/libLLVM/libLLVM/runtime.json).  Do I need a entry for `linux-x64`, if that's even possible, in order to get an actual runtime lib.so pulled down when doing the restore?  Or is there some trick/option I should be using to say, "for libLLVM use ubuntu18.4" ?

**Comment by tannergooding** [comment]
libLLVM is a native component generally built by LLVM and downloaded from the pre-built binaries: https://releases.llvm.org/download.html

As far as I know, there isn't a "generic" linux binary and so you need to actually resolve the underlying OS such as `ubuntu.18.04` or `ubuntu.16.04`. This might be something that the .NET SDK could handle better by passing in the actual OS version rather than the "generic OS version" so that things can be resolved more aptly.

**Comment by yowl** [comment]
Thanks, but how does https://www.nuget.org/packages/libLLVM.runtime.ubuntu.18.04-x64/ relate to the prebuilt binaries at https://releases.llvm.org/download.html?  Are you saying that I don't need to get it to resolve to a nuget package if I download from llvm.org directly and hence have the right .so in e.g. /usr/lib

**Comment by tannergooding** [comment]
The `libLLVM.runtime.ubuntu.18.04-x64` and related packages are created from the prebuilt binaries available at https://releases.llvm.org/download.html (when possible, there are a couple distro's that don't have `libLLVM.so` built by default).

> Are you saying that I don't need to get it to resolve to a nuget package if I download from llvm.org directly and hence have the right .so in e.g. /usr/lib

That should also work, but I was just trying to clarify that there isn't a `linux-x64` version and I don't believe we can create one.

**Comment by yowl** [comment]
I'm nearly there I think.  I understand about the RID problem with CoreRT so am pursuing how to get a `libLLVM.so`. The downloads from llvm.org don't contain the `.so` just the `.a`s.

```
root@DESKTOP-4SRE527:/tmp/clang+llvm-9.0.0-x86_64-linux-gnu-ubuntu-18.04# find . -name libLLVM.so -print
root@DESKTOP-4SRE527:/tmp/clang+llvm-9.0.0-x86_64-linux-gnu-ubuntu-18.04#                                          
```
So I thought I would see in the yml or scripts for LLVMSharp some library command (`ar` or `ld` maybe) that creates the `.so` from the `.a`s but I can't see that.

**Comment by yowl** [comment]
Will close as I believe there is nothing wrong here, and its just CoreRT's use of the RID `linux-x64` which is the problem.  `dotnet restore -r ubuntu.18.04-x64 libLLVMdep.depproj` and then a cp to /usr/lib is the workaround for me.
