### ISSUE TITLE
Reading ParamTypes of function types fails

### ISSUE THREAD

**Issue by TillAlex** [microsoft/LLVMSharp#134]
When reading the ParamTypes of function types an array with the correct number of elements is returned, but all returned types have 0x0 handles. These lines reproduce the issue:

```
var returnType = LLVMTypeRef.Int8;
var parameterTypes = new[] {LLVMTypeRef.Double};
var functionType = LLVMTypeRef.CreateFunction(returnType, parameterTypes);
Debug.Assert(parameterTypes.First() == functionType.ParamTypes.First()); // Fails
```

**Comment by TillAlex** [comment]
Thanks a lot! Would you mind pushing a new Nuget package?

**Comment by tannergooding** [comment]
I'll try to get a new package up this weekend.

I'm attempting to get some other changes in for 10.0.0 including `Span` overloads and a new "managed" API that mirrors the LLVM C++ API first.
