### ISSUE TITLE
createLocalVariable not generated in LLVM.cs

### ISSUE THREAD

**Issue by yowl** [microsoft/LLVMSharp#145]
If I understand correctly LLVM.cs is autogenerated ?  The debug function `createLocalVariable`  from DIBuilder.cpp is not present, perhaps because of the `SmallVector` in the signature?

```
static DILocalVariable *createLocalVariable(
    LLVMContext &VMContext,
    DenseMap<MDNode *, SmallVector<TrackingMDNodeRef, 1>> &PreservedVariables,
    DIScope *Scope, StringRef Name, unsigned ArgNo, DIFile *File,
    unsigned LineNo, DIType *Ty, bool AlwaysPreserve, DINode::DIFlags Flags,
    uint32_t AlignInBits) {
```

**Comment by tannergooding** [comment]
`createLocalVariable` is a private method that is part of the source files and isn't even available to normal C++ code.

`LLVMSharp` only exposes method signatures exported from the `llvm-c` public header files, notably: <https://github.com/llvm/llvm-project/tree/master/llvm/include/llvm-c>

**Comment by tannergooding** [comment]
C++ code has access to more, generally covering the public header files available here: <https://github.com/llvm/llvm-project/tree/master/llvm/include/llvm>

However, due to ABI differences and name mangling, consuming those from C#/.NET is non-trivial.

**Comment by yowl** [comment]
This one is important for getting access to locals in the debugger.  I think this parameter, which seems to be to do with preventing a variable getting inlined, could be null for now and if AlwaysPreseve == false, then its not used:
```
static DILocalVariable *createLocalVariable(
    LLVMContext &VMContext,
    DenseMap<MDNode *, SmallVector<TrackingMDNodeRef, 1>> &PreservedVariables,
    DIScope *Scope, StringRef Name, unsigned ArgNo, DIFile *File,
    unsigned LineNo, DIType *Ty, bool AlwaysPreserve, DINode::DIFlags Flags,
    uint32_t AlignInBits) {
  // FIXME: Why getNonCompileUnitScope()?
  // FIXME: Why is "!Context" okay here?
  // FIXME: Why doesn't this check for a subprogram or lexical block (AFAICT
  // the only valid scopes)?
  DIScope *Context = getNonCompileUnitScope(Scope);

  auto *Node =
      DILocalVariable::get(VMContext, cast_or_null<DILocalScope>(Context), Name,
                           File, LineNo, Ty, ArgNo, Flags, AlignInBits);
  if (AlwaysPreserve) {
    // The optimizer may remove local variables. If there is an interest
    // to preserve variable info in such situation then stash it in a
    // named mdnode.
    DISubprogram *Fn = getDISubprogram(Scope);
    assert(Fn && "Missing subprogram for local variable");
    PreservedVariables[Fn].emplace_back(Node);
  }
  return Node;
}
```

I'm going to try that with a local DllImport to see if I can get locals displaying, if it works maybe we could think about how to incorporate it, perhaps just without support for `AlwaysPreserve`?

**Comment by tannergooding** [comment]
I'm fairly certain you aren't meant to use that function and are instead meant to use things like `DIBuilder::createAutoVariable` and `DIBuilder::createParameterVariable`.

These are exposed via the C API as `LLVMDIBuilderCreateAutoVariable` and `LLVMDIBuilderCreateParameterVariable`, respectively.

**Comment by yowl** [comment]
Ah, you may be right, I was reading https://llvm.org/devmtg/2014-10/Slides/Christopher-DebugInfoTutorial.pdf which is very old.  I'll do some more investigation on `LLVMDIBuilderCreateAutoVariable `
