### ISSUE TITLE
Are there plans to support win-arm/win-arm64?

### ISSUE THREAD

**Issue by alexrp** [microsoft/LLVMSharp#147]
To be clear, I have no knowledge of whether LLVM/Clang even build on win-arm/win-arm64 at the moment. I'm just going through the list of targets I plan to support in my project and noticed that [LibLLVM](https://www.nuget.org/packages/libLLVM) doesn't have `win-arm`/`win-arm64` versions, so I'm wondering if there are plans to support these.

**Comment by tannergooding** [comment]
As of LLVM 12, there are official Windows ARM64 binaries being produce and so the 12.0.0 packages will support that.

There are no official ARM32 binaries and so that will continue to be unsupported.

**Comment by alexrp** [comment]
I seem to recall reading, at some point after opening the issue, that `win-arm` isn't going to be supported in .NET anymore? If that's right, then this issue can probably be closed.

**Comment by tannergooding** [comment]
It's currently only supported on Linux (specifically Debian and Ubuntu) and so is, even for those platforms, "blocked" until LLVM adds official support.
