### ISSUE TITLE
Could MarshaledString (and others) be made public?

### ISSUE THREAD

**Issue by jackoalan** [microsoft/LLVMSharp#152]
Since there is a considerable portion of the raw API bindings that aren't implemented in the managed bindings, some raw calls are required in special cases. Many of the unimplemented raw calls accept string parameters (e.g. `LLVM.AddModuleFlag`), but since `MarshaledString` is internal, the application needs to reinvent this wheel within its own assembly.

**Comment by tannergooding** [comment]
I think it would be better to just ensure the relevant overloads are exposed. I'm not completely against exposing `MarshaledString`, but just exposing things like `AddModuleFlag` on `LLVMModuleRef` seems like the overall better approach to this.
