### ISSUE TITLE
Would you consider adding libLLVM.lib to the nuget package ?

### ISSUE THREAD

**Issue by yowl** [microsoft/LLVMSharp#159]
For https://github.com/dotnet/runtimelab/pull/647 I'd like to use the same libLLVM.dll from c# and its corresponding .lib to build the clrjit.  Right now I can't link the clrjit.dll without a libLLVM.lib.  I think my only option at present is to build LLVMSharp myself so I can get the .lib,

**Comment by yowl** [comment]
I dont mean build LLVMSharp myself, IibLLVM.lib I would get by building llvm-project of course, but I suppose that as part of building LLVMSharp/libLVVM nugets you do have a libLLVM.lib that is built as part of your build of llvm-project?

**Comment by tannergooding** [comment]
Adding the lib is a fairly C/C++ centric scenario and is likely better acquired via a package manager that is "standard" in C++, such as `vcpkg` or `conan`.
You could also log a bug on `llvm-project` (https://bugs.llvm.org/) requesting they ship the `*.lib` files by default to better enable static linking scenarios.

The binaries built and distributed in NuGet are already fairly bulky and are oriented around supporting the managed .NET scenario.
