### ISSUE TITLE
Setting up build configurations

### ISSUE THREAD

**Issue by TChatzigiannakis** [microsoft/LLVMSharp#16]
There's the AnyCPU configuration in the solution, and the UnitTests project has a x64 target. But for some reason, the test runner in my VS seems to avoid x64.

In any case, I suggest we remove the AnyCPU configuration entirely (since we do have an unmanaged DLL anyway, so the whole project can't really be AnyCPU) and create just x86 and x64 build configurations. It will make the targets (and the intention) clearer to anyone building LLVMSharp from source.

If this is acceptable, I can create a quick PR right now.

**Comment by mjsabby** [comment]
Seems ok.

**Comment by mjsabby** [comment]
With work from Tanner, this issue is no longer relevant.
