### ISSUE TITLE
.net 5.0

### ISSUE THREAD

**Issue by Shadowblitz16** [microsoft/LLVMSharp#164]
can you release this for .net 5.0?

**Comment by ericsink** [comment]
Is something not working for you?  I use this with .net 5 every day.

**Comment by Shadowblitz16** [comment]
it doesn't seem to be on nuget for .net 5

**Comment by tannergooding** [comment]
You'll need to enable preview packages as the latest release is still beta: https://www.nuget.org/packages/LLVMSharp/11.0.0-beta

It is currently intentionally beta as the object oriented wrapper types are incomplete. I'm currently working on updating to LLVM 12 at which point I may split the library into two parts so we can have stable "raw" bindings and unstable object oriented wrapper types (at least until those are completed).

**Comment by Shadowblitz16** [comment]
ok thankyou
