### ISSUE TITLE
Make ReversePInvoke easier using LLVMSharp

### ISSUE THREAD

**Issue by mjsabby** [microsoft/LLVMSharp#23]
When a user calls into LLVMSharp and wants to ReversePInvoke (i.e. LLVM generated code calling into their C# code) it's a bit hard and (to be honest) mundane for the developer to write somewhat repetitive  code.

This is a very common scenario -- going to LLVM for some CPU intensive task and get the data, and then wanting the productivity of C# to deal with this data.

In fact, for a currently private project I have all the code that does on this fly and supports all C# and LLVM data types anyway, so why not just put that part into LLVMSharp?

Most likely co-ordinate with LLVM 3.7 release to expose this.

**Comment by mjsabby** [comment]
Obsolete

**Comment by aparajit-pratap** [comment]
@mjsabby why was this marked obsolete? Is there an easier way to call into managed code using LLVMSharp now? If so, please share.
