### ISSUE TITLE
Is LLVM.GetBufferStart supposed to return a string?

### ISSUE THREAD

**Issue by TChatzigiannakis** [Microsoft/LLVMSharp#39]
We have this declaration:

```
[DllImport(LibraryPath, EntryPoint = "LLVMGetBufferStart", CallingConvention = CallingConvention.Cdecl)]
public static extern string GetBufferStart(LLVMMemoryBufferRef memBuf);
```

We can see that [this function returns the `BufferStart` of a memory buffer](http://llvm.org/docs/doxygen/html/MemoryBuffer_8h_source.html#l00037). The type of that variable is `const char*`, not an `std::string` or an `llvm::StringRef`. It seems to me like our `LLVM.GetBufferStart` method should return an `IntPtr` (while another method or property should return the actual contents of the buffer).

Perhaps the `string` type on the C# side was chosen automatically by the code generator because of the `char*` type on the C side?

**Comment by mjsabby** [comment]
Fixed in https://github.com/Microsoft/LLVMSharp/commit/f7a521b133f8a3ae2cfc58cdb999aa879932c274
