### ISSUE TITLE
Make LLVMSharp .NET Core Compatible

### ISSUE THREAD

**Issue by mjsabby** [Microsoft/LLVMSharp#40]
Work involved is mostly building a new target that can reference the nuget .NET Core packages. We won't need much, I think only System.Runtime and System.Runtime.InteropServices.

**Comment by jkaye2012** [comment]
Has anyone thought about looking into this? It would be very helpful.

**Comment by mjsabby** [comment]
Take a look at this package, https://www.nuget.org/packages/LLVMSharp/3.9.1-rc1

Going forward LLVMSharp will require the user (that is you) to specify the location of the native library. On Windows we're debating whether we should still ship the native component (libLLVM.dll) since otherwise it's probably difficult for everyone to compile their own.

On Linux and macOS the story is that you'll use your distribution's library or compile from your source as is customary in the Linux world.

**Comment by jkaye2012** [comment]
Awesome. I'll check this out soon

**Comment by jkaye2012** [comment]
Looks like everything is installing with no issue. Would you expect the library to work on OSX with this release? Trying to load the LLVM library I get the following:

```
Unhandled Exception: System.Exception: LoadLibrary failed for: /usr/local/Cellar/llvm/3.9.1_1/lib/libLLVM.dylib
   at PInvokeHelpers.LoadLibrary(String )
   at LLVMSharp.LLVM.LoadLibrary_libLLVM(String nativeLibraryFilePath)
```

**Comment by jkaye2012** [comment]
Looks like this is happening for me on Windows as well. Any advice on how to load the LLVM library to make this work properly?

**Comment by jkaye2012** [comment]
@mjsabby Don't mean to be annoying, but is there any reference I can use to keep moving forward with my project? I've still been unable to get the LLVM library loaded in .NET Core (on any platform)

**Comment by jkaye2012** [comment]
Should I abandon all hope of this?

**Comment by jkotas** [comment]
It worked fine for me on Windows. Have you build the native LLVM library that you are trying to load - does the .dll/.dylib file from the error message exist?

**Comment by mjsabby** [comment]
@jkaye2012 sorry for the MIA here, we've got a plan to get us to LLVM 5.0 and the new .NET Core tooling by End of this month!

**Comment by ice1000** [comment]
Should this be closed? I see the maintainer pushed some changes that migrates to .net core 1.1

**Comment by ice1000** [comment]
Should this be closed? I see the maintainer pushed some changes that migrates to .net core 2.0
