### ISSUE TITLE
Use PInvokeCompiler for LLVMSharp to support .NET CoreRT and simplify deployment

### ISSUE THREAD

**Issue by mjsabby** [microsoft/LLVMSharp#49]
The main goal of this work item is to use the PInvokeCompiler toolchain (being developed @ http://github.com/PInvokeCompiler/PInvokeCompiler) and generate a single assembly that is runnable on:

.NET 4.0+
.NET Core
.NET CoreRT (AOT scenario)

This requires that we generate MSIL that does all the marshalling and bake it into the MSIL. This approach also has benefits for LLVMSharp beyond being able to run on CoreRT.

One key benefit is that now we will be able to use any LLVM.dll (or .so/.dylib) that is supplied to LLVMSharp and we don't have to be aware of where it is deployed. This need arises because a lot of scenarios (mostly in the Linux world) have LLVM installed on the system and they'd like to use that instead of a hypothetical one supplied with LLVMSharp (we don't supply one and don't want to).

This has one negative impact on LLVMSharp's usage which is that now we need to Initialize LLVMSharp before first use.

**Comment by TChatzigiannakis** [comment]
In this case, should `LLVMSharp.Api` be in a different assembly? Considering that we haven't automated the process of generating it the OOAPI, users who prefer or have to build the header files on their own, may want to just unload that part of the solution if their desired LLVM version doesn't match.

**Comment by mjsabby** [comment]
We have the DllImportResolver now, no need for this.
