### ISSUE TITLE
Add Object Oriented API that mirrors C++ API with objects for each instruction, value, etc.

### ISSUE THREAD

**Issue by mjsabby** [microsoft/LLVMSharp#5]
I've gotten feedback for the project (offline) that suggests that the debugging experience of the IR would be considerably better if we could dump the instructions that LLVMSharp is building so that one could use a debugger to visualize the data structure of a module, basic block, etc.

My assessment: The benefit is pretty clear. One of the best parts about developing in C# is the debugging experience in full-featured IDE's like Visual Studio.

It is a very large undertaking (probably 2-3 weeks).

**Comment by TChatzigiannakis** [comment]
Is it going to be generated from the LLVM C++ code base, or is it going to just mirror the C++ API while using the existing C/C# bindings behind the scenes?

If you're going for the latter, I could contribute to some degree, if you'd like (maybe in a separate branch/fork?).

**Comment by mjsabby** [comment]
It's the latter, and I absolutely would love help.

Take a look at: https://github.com/mjsabby/LLVMSharp/tree/OOAPIWorkInProgress

You can add to that.

I've got all the inheritance hierarchy with no code in the classes already there. It's a matter of filling them in.

Here's how I'm thinking about priority:

(1) IRBuilder
    (a) Add all the C++ variants like CreateRet ... from their doxygen document
    (b) As you add a new one you'll need to add it to the Conversions.cs (I have one for Value)
(2) Type
    (a) Fill in all the TypeRef's within the Type class.
(3) Terminator Instructions
    (a) Slightly tricky -- lots of successor, predecessor functions that we should expose but it would not be great if we have to duplicate the code.
(4) PasManager
(5) Module

Convention: get/set methods become properties, the rest of the names I follow literally. I'm putting comments on the top of the C# code with summary.

I'm happy for you take whichever in part, or in whole certain pieces.

How does one split up this work in GitHub?

**Comment by mjsabby** [comment]
I've updated the master branch with seed code, auto genned, so now the process starts to make it use the classes (instead of structs) in the OOAPIWorkInProgress branch. I'm sure there will be some merge issues. Sigh.

**Comment by mjsabby** [comment]
Obsolete, other work is being tracked elsewhere.
