### ISSUE TITLE
Example project on web page doesn't use fixed-width font and the right side of the code gets cut-off without scrollbars

### ISSUE THREAD

**Issue by chuckhacker** [Microsoft/LLVMSharp#53]
Linux Mint 18 + Chrome 54.0.2840.59 (64-bit)

Affected URL:
http://llvmsharp.org/

See screenshot:
http://imgur.com/a/QtWdc

**Comment by TheChuckster** [comment]
Any updates?

**Comment by mjsabby** [comment]
The website now redirects here.
