### ISSUE TITLE
Project deprecated?

### ISSUE THREAD

**Issue by sgf** [Microsoft/LLVMSharp#55]
http://www.clangsharp.org/ 
got 404 error
and seems project has no any update long times(seveal months)

https://github.com/dotnet/llilc seems deprecated too.

see kotlin native. progress is very fast.

hope this project wont be deprecated and do more faster....

**Comment by TChatzigiannakis** [comment]
Personally I have been busy with university and so I haven't contributed to my branch (OOAPI) for over a year. But I plan to pick it up immediately as soon as my workload decreases, since I need LLVM bindings for a project I'm already working on. So, at least as far as I'm concerned, it's not deprecated — but maybe we do need more contributors. =)

**Comment by kaby76** [comment]
I was wondering about the status, too. So instead, I've been working on a forked copy of the LLVM bindings library from SharpLang, which uses SWIG. The API is in Net Standard 1.1 and links with Net Standard/Core/Framework. But, it is limited by the built targets for LLVM 4.0, although I do have native libraries for Windows 32 and 64-bit, Ubuntu, and I'm working on the armeabi/x86 Android targets now. LLILC is not a C# API for LLVM, rather a LLVM backend for CIL. It's completely in C++, and it is not very easy to read. If you're interested in a LLVM backend for CIL, Mono Mini, also in C++, also a forked LLVM, is very easy to read. I saw this week someone releasing a GPU backend for CIL on NuGet, but there is no code in any of the repositories for the project.

**Comment by sgf** [comment]
I thought Llvmsharp was the official project for Microsoft employees.
to Microsoft employees as the main source of contribution.
ok.I wish I could help, but my technical is too slag. Just like C #.

**Comment by sirinath** [comment]
Can this be activated again along with llilc?

**Comment by TChatzigiannakis** [comment]
I personally intend to continue working on LLVMSharp soon. We can't speak on behalf of LLILC — it's an entirely different project.

**Comment by ice1000** [comment]
So when will this be updated...

**Comment by mjsabby** [comment]
Not deprecated, we're targeting end of month having it all updated to LLVM 5.0 along with using the new VS 2017 .NET Core tooling.

**Comment by sirinath** [comment]
Time to party!!!

**Comment by ice1000** [comment]
Can I just read the llvm cookbook (which uses C++) while getting started with this?

I'm working on a compiler recently (in C#, targeting llvm). Hope this official LLVM binding will work. 😃 Cheers!

**Comment by ice1000** [comment]
When will the LLVM-5 support be available?
When will the website reborn?

(Sorry for too many questions... 😜

**Comment by ice1000** [comment]
Can anyone help @mjsabby 

> When will the LLVM-5 support be available?
When will the website reborn?
Will you change the old APIs? If so, how much APIs will be changed? <br/><br/>
> (Sorry for too many questions... :stuck_out_tongue_winking_eye:

**Comment by mjsabby** [comment]
@ice1000 checkout https://nuget.org/packages/LLVMSharp -- LLVM-5 supoprt is available.

The website redirects here, since most of the information is here.

APIs are determined by the LLVM project, and we just make sure to keep them up-to-date.

**Comment by ice1000** [comment]
Nice! Thank you @mjsabby 

I should say this project is awesome! You guys are really doing something cool! :smiley:

**Comment by mjsabby** [comment]
The project is not deprecated. Closing this issue.
