### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ice1000** [Microsoft/LLVMSharp#59]
I'm translating the official doc (Kaleidoscope) into a C\# version.

It's in progress.

Link:

http://ice1000.org/llvm-cs/en/

I wonder if you can add the link to the README, and help me review+find bugs :smiley:

**Comment by mjsabby** [comment]
Sure, send a PR.

**Comment by ice1000** [comment]
Ok, I'll send pr when I finish and then close this issue.

**Comment by ice1000** [comment]
pr is sent. Replaced by #60
