### ISSUE TITLE
Wrong signature of LLVM.ConstIntOfArbitraryPrecision?

### ISSUE THREAD

**Issue by TChatzigiannakis** [Microsoft/LLVMSharp#63]
[LLVM documentation says](http://llvm.org/doxygen/group__LLVMCCoreValueConstantScalar.html#ga3ce3363ae52e157bbc63c9fde4aa3821) that the last parameter of `LLVMConstIntOfArbitraryPrecision()` is `const uint64_t[]` but we have it as `int[]`. I think it should be `ulong[]`.

**Comment by ice1000** [comment]
Please fix this :sob:
