### ISSUE TITLE
Feedback on the OOAPI

### ISSUE THREAD

**Issue by TChatzigiannakis** [microsoft/LLVMSharp#64]
I've pushed a version of the `LLVMSharp.Api` namespace that contains almost all of the functionality of the original C bindings in a form that (roughly) mimcs the C++ API but in a style that feels more like a C# library (getters/setters, IDisposable interface, generic delegates, cleaner identifiers, etc).

If anyone wants to try it and give some feedback on how to improve it, please go to the [OOAPIWorkInProgress](https://github.com/Microsoft/LLVMSharp/tree/OOAPIWorkInProgress) branch and build that solution. There are tests included that can be used as examples.

**Comment by onionhammer** [comment]
This looks really great so far!

**Comment by smaillet** [comment]
Now that this repo seems to be getting some attention again we might want to have a discussion on how we can merge/join/collaborate with the [Llvm.NET](https://github.com/UbiquityDotNET/Llvm.NET) project it has a very robust OO model that is built on a low level interop projection similar to this project, as  a ignificantly extended superset of the LLVM-C API  (thought it deliberately hides the raw low level interop in favor of a proper .NET OO model).
The OO model was used and tested in the Llilium project and a new AOT engine under development, so it has some miles on it. The automated builds keeps the [Current API docs](https://ubiquitydotnet.github.io/Llvm.NET/) in sync with the current code base.

**Comment by mjsabby** [comment]
@TChatzigiannakis given the recent work, is this issue obsolete?

**Comment by TChatzigiannakis** [comment]
@mjsabby I'd say so, yes.
