### ISSUE TITLE
LLVM 4.0.1 support?

### ISSUE THREAD

**Issue by christianscheuer** [Microsoft/LLVMSharp#66]
Would it be possible to create a build with support for LLVM 4.0?
CoreRT is currently tied to latest Emscripten release, which uses LLVM 4, and so cannot update to LLVMSharp v5.
We could look at producing the LLVMSharp bindings ourselves, but there doesn't seem to be a publicly available repo for building the libLLVM dependency (which also has no v4 releases).

**Comment by mjsabby** [comment]
@christianscheuer LLVM 4.0 package is now on nugget. Let me know if this address your issue and we can close it out.

**Comment by christianscheuer** [comment]
@mjsabby yes thank you for solving this!
