### ISSUE TITLE
Document DLL creation

### ISSUE THREAD

**Issue by frederik-h** [Microsoft/LLVMSharp#70]
As far as I can see, there are at least two non-equivalent ways to build the libLLVM.dll: using the powershell script in the tools directory and using the MSBuild project in tools/libLLVM. 
The latter variant seems to be less flexible. For instance, the LLVM libraries for many target architectures are hard-coded as dependencies and I am only interested in the x86 target architecture. 
What is the preferred way to build the DLL? Would it be reasonable to use the powershell script in the MSBuild project or to have an alternative project which uses the script?

**Comment by mjsabby** [comment]
@frederik-h the latter can be more useful since we'll need to add apis missing from the C libraries. But I'm going to clean this up as we add DIBuilder support. It'll probably be the latter.

If those hardcoded values are removed, does that solve your problem?

**Comment by frederik-h** [comment]
Yes, that would probably solve the problem. Currently, I use an adapted version of the powershell script and I have an MSBuild project which calls the script.
