### ISSUE TITLE
Could not install package 'LibLLVM 5.0.1'

### ISSUE THREAD

**Issue by howion** [Microsoft/LLVMSharp#73]
When i run **`Install-Package LLVMSharp -Version 5.0.0`** on **Package Manager Console** im getting error down below.

![image](https://user-images.githubusercontent.com/39840945/43616194-f866eada-96c3-11e8-81be-baf0d5a8c922.png)

**Comment by peacecwz** [comment]
@howion You cannot install this package under .NET Framework v4.6.1. You have to upgrade to .NET Framework v4.6.1, .NET Standard v1.6.1 or higher

**Comment by peacecwz** [comment]
@howion If it's answer to your issue, you can close this issue :)

**Comment by howion** [comment]
Thanks. Solved with upgrading to .NET Framework  4.7. But i think readme.md should be updated

**Comment by howion** [comment]
**Solved** with upgrading to **.NET Framework 4.7** But i think readme.md should be updated then
![image](https://user-images.githubusercontent.com/39840945/44615383-e39f2b00-a841-11e8-904f-be53e74a3e47.png)
Because 4+ contains 4.5.2 idk anyway, solved Thanks :D

**Comment by peacecwz** [comment]
Yeah, you are right. You can look dependencies on Nuget. You will see it there
