### ISSUE TITLE
Add SourceLink for libLLVM.dll

### ISSUE THREAD

**Issue by mjsabby** [microsoft/LLVMSharp#78]
VS 2017 15.8 supports SourceLink for C++ projects.

https://docs.microsoft.com/en-us/cpp/build/reference/sourcelink?view=vs-2017

This will allow libLLVM.dll to be debugged into with sources indexed on a GIT repo for a particular release.

**Comment by tannergooding** [comment]
This is probably an issue that should be opened against libLLVM and libClang proper as ideally we would move entirely to pre-built binaries.

**Comment by mjsabby** [comment]
Now that you have everything building as such it probably does make sense that way. We may have to move till their GitHub move.
