### ISSUE TITLE
Segmentation fault when using LLVM.IsA... methods

### ISSUE THREAD

**Issue by jangofett4** [Microsoft/LLVMSharp#89]
LibLLVM Version 5.0.1
.Net Core 2.1 Project

EDIT: See below

Example code:
```
...
LLVMValueRef fnexp = Visit(context.expr()); // Returns a pointer to a function
if (LLVM.IsAFunction(fnexp).IsNull())
    {
        Console.WriteLine("Error: Expression is not a function: {0} (Expected: Function, got {1})", context.expr().GetText(), fnexp.TypeOf().TypeKind);
        return TealHelper.Null;
...
```
Visual Studio: ![image](https://user-images.githubusercontent.com/19552452/53172081-83712200-35f5-11e9-818b-7ae6204b71af.png)

Pointer is not 0, so it shouldn't segfault. But LLVM.IsAFunction returns nullptr no matter what.

Other tries:

```
var fnexp = Visit(context.expr());
var isfn = fnexp.IsAFunction();
if (isfn.IsNull())
{
	Console.WriteLine("Error: Expression is not a function: {0} (Expected: Function, got {1})", context.expr().GetText(), fnexp.TypeOf().TypeKind);
	return TealHelper.Null;
}
```
Visual Studio: 
![image](https://user-images.githubusercontent.com/19552452/53172340-21fd8300-35f6-11e9-8460-8ec11db36b15.png)

Also tried to change expression to:
`if (isfn.Pointer == IntPtr.Zero)`
This way It does not segfault, instead expression becomes true everytime!

Also all of the LLVM.IsA... methods seem to return null pointer

# Update:
I get it to work, problem was I testing if a pointer is a function and `LLVM.IsAFunction(...)` was returning a nullptr (instead of something more convenient). I also had problems with other LLVM.IsA.. methods and LLVM.GetBasicBlockName(...) method.

Edited example code provided in readme of this repo:
```
private static void Main(string[] args)
{
            LLVMBool Success = new LLVMBool(0);
            LLVMModuleRef mod = LLVM.ModuleCreateWithName("LLVMSharpIntro");

            LLVMTypeRef[] param_types = { LLVM.Int32Type(), LLVM.Int32Type() };
            LLVMTypeRef ret_type = LLVM.FunctionType(LLVM.Int32Type(), param_types, false);
            LLVMValueRef sum = LLVM.AddFunction(mod, "sum", ret_type);

            LLVMBasicBlockRef entry = LLVM.AppendBasicBlock(sum, "entry");

            LLVMBuilderRef builder = LLVM.CreateBuilder();
            LLVM.PositionBuilderAtEnd(builder, entry);
            LLVMValueRef tmp = LLVM.BuildAdd(builder, LLVM.GetParam(sum, 0), LLVM.GetParam(sum, 1), "tmp");
            LLVM.BuildRet(builder, tmp);

            if (LLVM.VerifyModule(mod, LLVMVerifierFailureAction.LLVMPrintMessageAction, out var error) != Success)
            {
                Console.WriteLine($"Error: {error}");
            }

            LLVM.DumpModule(mod);
            Console.WriteLine(LLVM.GetBasicBlockName(entry));

            LLVM.DisposeBuilder(builder);
            Console.WriteLine("END.");
            Console.ReadKey(true);
}
```
(Sorry for cancerous indentation, I had to cut some parts out)

Visual Studio and program output:
![image](https://user-images.githubusercontent.com/19552452/53229129-70f9f580-3694-11e9-899d-3290f4d6ba17.png)

This code is from readme of this repository (same until `LLVM.DumpModule`)
I had to break at `GetBasicBlockName` because application just crashes without a trace at that statement. No segfaulting this time. Application waits like 2 seconds and then closes itself. Program never sees `LLVM.DisposeBuilder` nor `Console.WriteLine`

**Comment by mjsabby** [comment]
@TChatzigiannakis is this the OOP stuff?

**Comment by jangofett4** [comment]
I fixed the problem (partially). The problem was I was sending a LLVMValueRef that points to a pointer to a function (a.k.a variable pointing to a function). After trying it with a function, it returned correct value. But this doesn't change the fact when non-function value passed to LLVM.IsAFunction method returns a nullptr. (I guess this is a property of LLVM instead?)
Also LLVM.GetBasicBlockName definitely does not work. Segfaults whatever I do.

I will edit the issue tomorrow.

**Comment by yowl** [comment]
I don't know if its the same but the following also throws an access violation
```
            LLVMBuilderRef landingPadBuilder = LLVM.CreateBuilder();
            LLVM.PositionBuilderAtEnd(landingPadBuilder, landingPad);
            LLVMValueRef pad = LLVM.BuildLandingPad(landingPadBuilder, LLVM.PointerType(LLVM.Int8Type(), 0), GxxPersonality, 1, "");
            LLVM.AddClause(pad, LLVM.ConstPointerNull(LLVM.PointerType(LLVM.Int8Type(), 0)));
            var exPtr = LLVM.BuildExtractValue(landingPadBuilder, pad, 0, "ex");
```
on the `BuildExtractValue`

**Comment by yowl** [comment]
My bad, the personality signature is wrong.

**Comment by mjsabby** [comment]
Debugging this stuff can get annoying. As I'm doing the work to get the native stuff automated, I'm thinking we should also publish a debug build of LLVMSharp with native pieces built as debug too with symbols uploaded. This way you'll also get the asserts.

**Comment by TChatzigiannakis** [comment]
@jangofett4 Is it possible to provide a minimal snippet that reproduces this, so I can take it and step through it? (I realize that this problem may be manifesting itself only in a complicated scenario in your codebase, but if by any chance you can extract the valuable parts to a self-contained piece of code, it would make things much easier.)

**Comment by TChatzigiannakis** [comment]
@jangofett4 It's been a while since I last used them, but I seem to recall that the `LLVM.IsA<X>` family of functions simply return a `NULL` pointer if the handle passed to does not point to a `<X>` -- otherwise, I think, it returns the argument. (This is LLVM behavior, not LLVMSharp-specific.)

Regarding `LLVM.GetBasicBlockName`, can you provide a minimal example that can reproduce this? I suspect this is a LLVMSharp problem, specifically marshalling may be failing on edge cases like empty strings. I recall encountering this problem with some other methods, which is why I introduced [a few internal overloads that return `IntPtr` instead of `string`](https://github.com/Microsoft/LLVMSharp/blob/master/src/Overloads.Interop.cs) and [I explicitly unpack it](https://github.com/Microsoft/LLVMSharp/blob/master/src/Api/Target.cs#L39) internally in the `LLVMSharp.API` methods. Perhaps something similar should be done here, I'll look into it later.

**Comment by jangofett4** [comment]
@TChatzigiannakis thanks for clarifying. I will close this one and create a new one related to `LLVM.GetBasicBlockName`.
