### ISSUE TITLE
[question] Get LL (IR) code from a module?

### ISSUE THREAD

**Issue by cloudrex** [Microsoft/LLVMSharp#94]
How can I get the IR code generated by a module, into a string variable? I've found `LLVM.DumpModule()` but that directly outputs it, I've tried `module.ToString()` but that returns the conventional type-string.

Any ideas?

**Comment by cloudrex** [comment]
Found it.

**Comment by ice1000** [comment]
What did you find?

**Comment by cloudrex** [comment]
I used `LLVM.PrintModuleToString()` then `Marshal.PtrToStringAnsi()`.

It shouldn't be that hard tho...

**Comment by TChatzigiannakis** [comment]
You can also consider using the `LLVMSharp.Api` classes. [They take care of such things](https://github.com/Microsoft/LLVMSharp/blob/master/src/Api/Module.cs#L42) for you.
